from typing import Callable, Tuple

import jax 
import jax.numpy as jnp
from jax import random, lax
import equinox as eqx 

class SLIPSParams(eqx.Module):
    """
    Parameters for the SLIPS algorithm.
    Object to be passed to the geom_slips function, which contains all
    the parameters for the algorithm.
    """
    # Dynamic params
    sigma: float
    
    # Dynamic named params
    alpha_1: float = 1.0
    alpha_2: float = 1.0
    target_accept: float = 0.75
    step_min: float = 1e-2
    step_max: float = 1e2
    learning_rate: float = 2.0

    # Static named params
    n_mcmc_steps:   int   = eqx.field(default=32, static=True)
    n_chains:       int   = eqx.field(default=4, static=True)          
    n_init_steps:   int   = eqx.field(default=32, static=True)
    burn_in_ratio:  float = eqx.field(default=0.5, static=True)
    return_history: bool  = eqx.field(default=False, static=True)



def _single_mala(key: jax.Array, 
                 init_x: jax.Array, 
                 log_and_score: Callable, 
                 step_size: float, 
                 params: SLIPSParams) -> Tuple[jax.Array, jax.Array, float]: 
    
    """
    Single MALA run for a single chain. 
    This function is vectorized over chains in the _mala function.
    It is meant to be used inside the SLIPS algorithm, and 
    is not meant to be used directly.

    Parameters
    ----------
        key: jax.Array
            Random key for JAX random number generation.
        init_x: jax.Array
            Initial position of the chain.
        log_and_score: Callable
            Function that takes in a position and returns the log probability and score.
        step_size: float
            Step size for the MALA algorithm.
        params: SLIPSParams
            Parameters for the SLIPS algorithm.
    Returns
    -------
    chain: jax.Array
        The chain of samples generated by the MALA algorithm.
    final_x: jax.Array
        The final position of the chain after n_mcmc_steps.
    accept_rate: float
        The acceptance rate of the MALA algorithm.
    """
    
    def step(carry: Tuple[jax.Array, jax.Array, jax.Array, jax.Array, jax.Array],
             i: int) -> Tuple[Tuple[jax.Array, jax.Array, jax.Array, jax.Array, jax.Array], jax.Array]:
        sample, score, log_pdf, accepts, key = carry
        key, key_dW, key_u = random.split(key, num=3)

        dW = random.normal(key_dW, (sample.shape))

        sample_new = sample + step_size*score + jnp.sqrt(2*step_size)*dW

        log_pdf_new, score_new = log_and_score(sample_new)

        d = sample - sample_new - step_size*score_new

        log_q = -1.0/(4*step_size) * jnp.sum(d**2)
        log_q_new = -0.5 * jnp.sum(dW**2)

        log_alpha = log_pdf_new - log_pdf + log_q - log_q_new

        accept_mask = jnp.log(random.uniform(key_u)) < log_alpha

        sample = jnp.where(accept_mask, sample_new, sample)

        score = jnp.where(accept_mask, score_new, score)
        log_pdf = jnp.where(accept_mask, log_pdf_new, log_pdf)
        accepts += accept_mask.astype(accepts.dtype)

        return (sample, score, log_pdf, accepts, key), sample

    init_log_pdf, init_score = log_and_score(init_x)
    (final_x, _, _, accepts, _), chain = lax.scan(step,(init_x, init_score, init_log_pdf, 0.0, key),length=params.n_mcmc_steps)

    return chain, final_x, accepts/params.n_mcmc_steps



# Vectorize the mala over chains, to run several chains in parallel
_mala = jax.vmap(_single_mala, in_axes=(0, 0, None, None, None))



def _single_slips(key: jax.Array,
                  log_target: Callable,
                  time_grid: jax.Array, 
                  dim: int,
                  params: SLIPSParams) -> Tuple:
    """
    Single SLIPS run for a single sample with a non-asymptotic geometric
    schedule.
    This function is vectorized over samples in the geom_slips function.
    It is meant to be used inside the geom_slips function, and 
    is not meant to be used directly.   

    Parameters
    ----------
        key: jax.Array
            Random key for JAX random number generation.
        log_target: Callable
            Function that takes in a position and returns the log probability.
        time_grid: jax.Array
            Array of time points for the SLIPS algorithm.
        dim: int
            Dimension of the target distribution.
        params: SLIPSParams
            Parameters for the SLIPS algorithm.
    Returns
    -------
    Y_final: jax.Array
        The final sample generated by the SLIPS algorithm.
    Y_hist: jax.Array
        The history of samples generated by the SLIPS algorithm.
    X_hist: jax.Array
        The history of MALA chains generated by the SLIPS algorithm.
    """

    def g(t: float) -> float: return (t**(params.alpha_1/2))*((1-t)**(-params.alpha_2/2))
    def alpha(t: float) -> float: return t**(1/2)*g(t)
    def log_mu(x: jax.Array, y: jax.Array, t: float) -> jax.Array:
            return log_target(x) - 0.5 * jnp.sum(((x - y / alpha(t)) / (params.sigma / g(t)))**2)

    log_pdf_and_score = jax.value_and_grad(log_mu)

    t0 = time_grid[0]
    alpha_0 = alpha(t0)
    step_size_init = params.sigma*jnp.sqrt(t0)

    dts = jnp.diff(time_grid)
    diff_alpha = jnp.diff(alpha(time_grid))

    key, key_y, key_init = random.split(key, num=3)

    Y = params.sigma * jnp.sqrt(t0) * random.normal(key_y, (dim,))
    X = jnp.broadcast_to(Y / alpha_0, (params.n_chains, dim))
    
    def init_step(i: int, 
                  val: Tuple[jax.Array, jax.Array, float, jax.Array]) -> Tuple[jax.Array, jax.Array, float, jax.Array]:

        y_curr, x_curr, step_size, key = val

        key, key_mala, key_y = random.split(key, 3)
        keys_mala = random.split(key_mala, params.n_chains)

        def log_pdf_and_score_curr(x: jax.Array) -> jax.Array:
            return log_pdf_and_score(x, y_curr, t0)

        chains, x_curr, accept_rate = _mala(keys_mala, x_curr, log_pdf_and_score_curr, step_size, params)


        step_size *= jnp.exp(params.learning_rate*(jnp.mean(accept_rate) - params.target_accept))
        step_size = jnp.clip(step_size, a_min=params.step_min, a_max=params.step_max)

        burn_in_idx = int(params.n_mcmc_steps*params.burn_in_ratio)
        denoiser = jnp.mean(chains[:, burn_in_idx:, :], axis=(0, 1))

        y_curr = y_curr/2.0 + alpha_0*denoiser/2.0 + params.sigma*jnp.sqrt(t0)*random.normal(key_y,(dim,))

        return (y_curr, x_curr, step_size, key)
    
    (Y,X,step_size,key) = lax.fori_loop(0, params.n_init_steps, init_step, (Y,X,step_size_init,key_init))

    def main_step(carry: Tuple[jax.Array, jax.Array, float, jax.Array], 
                  i: int) -> Tuple[jax.Array, jax.Array, float, jax.Array]:
        # Explain shapes
        y_curr, x_curr, step_size, key = carry

        key, key_mala, key_y = random.split(key, 3)
        keys_mala = random.split(key_mala, params.n_chains)

        dt = dts[i]
        t = time_grid[i]
        d_alpha = diff_alpha[i]

        def log_pdf_and_score_curr(x: jax.Array) -> jax.Array:
            return log_pdf_and_score(x, y_curr, t)
        
        chains, x_curr, accept_rate = _mala(keys_mala, x_curr, log_pdf_and_score_curr, step_size, params)

        step_size *= jnp.exp(params.learning_rate*(jnp.mean(accept_rate) - params.target_accept))
        step_size = jnp.clip(step_size, a_min=params.step_min, a_max=params.step_max)

        burn_in_idx = int(params.n_mcmc_steps*params.burn_in_ratio)
        denoiser = jnp.mean(chains[:, burn_in_idx:, :], axis=(0, 1))
        score_Y = d_alpha*denoiser

        y_curr = y_curr+ score_Y + params.sigma*jnp.sqrt(dt)*random.normal(key_y,(dim,))

        return (y_curr, x_curr, step_size, key), (y_curr, x_curr)
    
    if params.return_history:
        (Y, X, _, _), (Y_hist, X_hist) = lax.scan(
            main_step, (Y, X, step_size, key), jnp.arange(len(dts))
        )

        return Y/alpha(time_grid[-1]), Y_hist, X_hist
    else:
        def fori_main_step(i: int, 
                           carry: Tuple[jax.Array, jax.Array, float, jax.Array]) -> Tuple[jax.Array, jax.Array, float, jax.Array]:
            carry, _ = main_step(carry, i)
            return carry
        
        (Y, X, _, _) = lax.fori_loop(
            0, len(dts), fori_main_step, (Y, X, step_size, key)
        )
        return Y/alpha(time_grid[-1])



# Vmap the single-item solver over the batch of keys
_slips = eqx.filter_vmap(
    _single_slips, 
    in_axes=(0, None, None, None, None)
)



@eqx.filter_jit
def geom_slips(key: jax.Array,
               log_target: Callable[[jax.Array], jax.Array],
               time_grid: jax.Array,
               batch_size: int,
               dim: int, 
               params: SLIPSParams) -> Tuple:
    """
    Non-asymptotic geometric schedule SLIPS algorithm for sampling from a target distribution.

    Parameters
    ----------
        key: jax.Array
            Random key for JAX random number generation.
        log_target: Callable[[jax.Array], jax.Array]
            Function that compute the log probability of the target distribution.
            It is meant to be made with JAX, and should be `jit`-compiled and `vmap`ped.
        time_grid: jax.Array
            Array of time points for the SLIPS algorithm.
        batch_size: int
            Number of samples to generate.
        dim: int
            Dimension of the target distribution.
        params: SLIPSParams
            Parameters for the SLIPS algorithm (see `SLIPSParams` class).
    Returns 
    -------
    samples: jax.Array
        The final samples generated by the SLIPS algorithm.
    Y_hist: jax.Array
        The history of samples generated by the SLIPS algorithm.
    X_hist: jax.Array
        The history of MALA chains generated by the SLIPS algorithm.

    Example
    -------
    >>> key = jax.random.PRNGKey(42)
    >>> log_target = lambda x: -jnp.sum(((x-6)/2)**2)/2
    >>> time_grid = jnp.linspace(0.1,0.98)
    >>> batch_size = 2
    >>> dim = 1
    >>> params = SLIPSParams(10.0)
    >>> samples = geom_slips(key, log_target, time_grid, batch_size, dim, params)
    >>> print(samples)
    """

    time_grid = eqx.error_if(time_grid, time_grid[0] <= 0, "time_grid[0] must be strictly > 0")
    time_grid = eqx.error_if(time_grid, time_grid[-1] >= 1, "time_grid[-1] must be strictly < 1 for the Geom schedule")
    
    keys = random.split(key, batch_size)
    return _slips(keys, log_target, time_grid, dim, params)

    

    
    