from typing import Callable, Tuple

import jax 
import jax.numpy as jnp
from jax import random, lax

from .params import SLIPSParams

def _single_mala(key: jax.Array, 
                 init_x: jax.Array, 
                 log_and_score: Callable, 
                 step_size: float, 
                 params: SLIPSParams) -> Tuple[jax.Array, jax.Array, float]: 
    
    """
    Single MALA run for a single chain. 
    This function is vectorized over chains in the _mala function.
    It is meant to be used inside the SLIPS algorithm, and 
    is not meant to be used directly.

    Parameters
    ----------
        key: jax.Array
            Random key for JAX random number generation.
        init_x: jax.Array
            Initial position of the chain.
        log_and_score: Callable
            Function that takes in a position and returns the log probability and score.
        step_size: float
            Step size for the MALA algorithm.
        params: SLIPSParams
            Parameters for the SLIPS algorithm.
    Returns
    -------
    chain: jax.Array
        The chain of samples generated by the MALA algorithm.
    final_x: jax.Array
        The final position of the chain after n_mcmc_steps.
    accept_rate: float
        The acceptance rate of the MALA algorithm.
    """
    
    def step(carry: Tuple[jax.Array, jax.Array, jax.Array, jax.Array, jax.Array],
             i: int) -> Tuple[Tuple[jax.Array, jax.Array, jax.Array, jax.Array, jax.Array], jax.Array]:
        sample, score, log_pdf, accepts, key = carry
        key, key_dW, key_u = random.split(key, num=3)

        # Proposal
        dW = random.normal(key_dW, (sample.shape))
        sample_new = sample + step_size*score + jnp.sqrt(2*step_size)*dW

        # Evaluate log pdf and score at new sample, compute alpha
        log_pdf_new, score_new = log_and_score(sample_new)
        d = sample - sample_new - step_size*score_new

        log_q = -1.0/(4*step_size) * jnp.sum(d**2)
        log_q_new = -0.5 * jnp.sum(dW**2)

        log_alpha = log_pdf_new - log_pdf + log_q - log_q_new

        # Accept or reject
        accept_mask = jnp.log(random.uniform(key_u)) < log_alpha

        sample = jnp.where(accept_mask, sample_new, sample)

        # Pass the score and log_pdf from one iteration to the next,
        # to avoid recomputing them for the accepted samples
        score = jnp.where(accept_mask, score_new, score)
        log_pdf = jnp.where(accept_mask, log_pdf_new, log_pdf)

        # Number of accepted samples, to compute the acceptance
        # rate at the end of the MALA run
        accepts += accept_mask.astype(accepts.dtype)

        return (sample, score, log_pdf, accepts, key), sample

    init_log_pdf, init_score = log_and_score(init_x)
    (final_x, _, _, accepts, _), chain = lax.scan(step,(init_x, init_score, init_log_pdf, 0.0, key),length=params.n_mcmc_steps)

    return chain, final_x, accepts/params.n_mcmc_steps



# Vectorize the mala over chains, to run several chains in parallel
_mala = jax.vmap(_single_mala, in_axes=(0, 0, None, None, None))
