from typing import Callable, Tuple

import jax 
import jax.numpy as jnp
from jax import random, lax
import equinox as eqx 

from .params import SLIPSParams
from .mala import _mala
from .schedules import Schedule, StandardSchedule, GeomSchedule


def _single_slips(key: jax.Array,
                  log_target: Callable,
                  time_grid: jax.Array, 
                  dim: int,
                  params: SLIPSParams) -> Tuple:
    """
    Single SLIPS run for a single sample with a non-asymptotic geometric
    schedule.
    This function is vectorized over samples in the slips function.
    It is meant to be used inside the slips function, and 
    is not meant to be used directly.   

    Parameters
    ----------
        key: jax.Array
            Random key for JAX random number generation.
        log_target: Callable
            Function that takes in a position and returns the log probability.
        time_grid: jax.Array
            Array of time points for the SLIPS algorithm.
        dim: int
            Dimension of the target distribution.
        params: SLIPSParams
            Parameters for the SLIPS algorithm.
    Returns
    -------
    Y_final: jax.Array
        The final sample generated by the SLIPS algorithm.
    Y_hist: jax.Array
        The history of samples generated by the SLIPS algorithm.
    X_hist: jax.Array
        The history of MALA chains generated by the SLIPS algorithm.
    """

    # log-mu function, as defined in the paper
    def log_mu(x: jax.Array, y: jax.Array, t: float) -> jax.Array:
            return log_target(x) - 0.5 * jnp.sum(((x - y / params.schedule.alpha(t)) / (params.sigma / params.schedule.g(t)))**2)

    log_pdf_and_score = jax.value_and_grad(log_mu)

    t0 = time_grid[0]
    alpha_0 = params.schedule.alpha(t0)

    # The step size for the MALA algorithm 
    # Each element of the batch has its own step size,
    # which is adapted after each run of the MALA algorithm based on the
    # previous acceptance rate of the MALA run
    step_size_init = params.sigma*jnp.sqrt(t0)

    dts = jnp.diff(time_grid)
    diff_alpha = jnp.diff(params.schedule.alpha(time_grid))

    key, key_y, key_init = random.split(key, num=3)

    # Y represents the current sample, X represents the current MALA chain state
    Y = params.sigma * jnp.sqrt(t0) * random.normal(key_y, (dim,))
    X = jnp.broadcast_to(Y / alpha_0, (params.n_chains, dim))
    
    # Function which does a single iteration of the
    # Langevin-within-Langevin algorithm, defined in Algorithm 2
    def init_step(i: int, 
                  val: Tuple[jax.Array, jax.Array, float, jax.Array]) -> Tuple[jax.Array, jax.Array, float, jax.Array]:

        y_curr, x_curr, step_size, key = val

        key, key_mala, key_y = random.split(key, 3)
        keys_mala = random.split(key_mala, params.n_chains)

        def log_pdf_and_score_curr(x: jax.Array) -> jax.Array:
            return log_pdf_and_score(x, y_curr, t0)

        # Run MALA
        chains, x_curr, accept_rate = _mala(keys_mala, x_curr, log_pdf_and_score_curr, step_size, params)

        # Adapt the step size of the MALA algorithm based on the acceptance rate
        step_size *= jnp.exp(params.learning_rate*(jnp.mean(accept_rate) - params.target_accept))
        step_size = jnp.clip(step_size, min=params.step_min, max=params.step_max)

        # The denoiser is estimated not only by the last sample of the MALA chain, 
        # but by the average of all samples after the burn-in period
        burn_in_idx = int(params.n_mcmc_steps*params.burn_in_ratio)
        denoiser = jnp.mean(chains[:, burn_in_idx:, :], axis=(0, 1))

        y_curr = y_curr/2.0 + alpha_0*denoiser/2.0 + params.sigma*jnp.sqrt(t0)*random.normal(key_y,(dim,))

        return (y_curr, x_curr, step_size, key)
    
    (Y,X,step_size,key) = lax.fori_loop(0, params.n_init_steps, init_step, (Y,X,step_size_init,key_init))

    def main_step(carry: Tuple[jax.Array, jax.Array, float, jax.Array], 
                  i: int) -> Tuple[jax.Array, jax.Array, float, jax.Array]:
        y_curr, x_curr, step_size, key = carry

        key, key_mala, key_y = random.split(key, 3)
        keys_mala = random.split(key_mala, params.n_chains)

        dt = dts[i]
        t = time_grid[i]
        d_alpha = diff_alpha[i]

        def log_pdf_and_score_curr(x: jax.Array) -> jax.Array:
            return log_pdf_and_score(x, y_curr, t)
        
        # Run MALA
        chains, x_curr, accept_rate = _mala(keys_mala, x_curr, log_pdf_and_score_curr, step_size, params)

        # Adapt the step size of the MALA algorithm based on the acceptance rate
        step_size *= jnp.exp(params.learning_rate*(jnp.mean(accept_rate) - params.target_accept))
        step_size = jnp.clip(step_size, min=params.step_min, max=params.step_max)

        # The denoiser is estimated not only by the last sample of the MALA chain, 
        # but by the average of all samples after the burn-in period
        burn_in_idx = int(params.n_mcmc_steps*params.burn_in_ratio)
        denoiser = jnp.mean(chains[:, burn_in_idx:, :], axis=(0, 1))
        score_Y = d_alpha*denoiser

        y_curr = y_curr+ score_Y + params.sigma*jnp.sqrt(dt)*random.normal(key_y,(dim,))

        return (y_curr, x_curr, step_size, key), (y_curr, x_curr)
    
    # Depending on the value of return_history, either run lax.scan or
    # lax.fori_loop to compute the final sample and the history of samples
    if params.return_history:
        (Y, X, _, _), (Y_hist, X_hist) = lax.scan(
            main_step, (Y, X, step_size, key), jnp.arange(len(dts))
        )

        return Y/params.schedule.alpha(time_grid[-1]), Y_hist, X_hist
    else:
        def fori_main_step(i: int, 
                           carry: Tuple[jax.Array, jax.Array, float, jax.Array]) -> Tuple[jax.Array, jax.Array, float, jax.Array]:
            carry, _ = main_step(carry, i)
            return carry
        
        (Y, X, _, _) = lax.fori_loop(
            0, len(dts), fori_main_step, (Y, X, step_size, key)
        )
        return Y/params.schedule.alpha(time_grid[-1])



# Vmap the single-item solver over the batch of keys
_slips = eqx.filter_vmap(
    _single_slips, 
    in_axes=(0, None, None, None, None)
)


@eqx.filter_jit
def slips(key: jax.Array,
               log_target: Callable[[jax.Array], jax.Array],
               time_grid: jax.Array,
               batch_size: int,
               dim: int, 
               params: SLIPSParams) -> Tuple:
    """
    Non-asymptotic geometric schedule SLIPS algorithm for sampling from a target distribution.

    Parameters
    ----------
        key: jax.Array
            Random key for JAX random number generation.
        log_target: Callable[[jax.Array], jax.Array]
            Function that compute the log probability of the target distribution.
            It is meant to be made with JAX, and should be `jit`-compiled and `vmap`ped.
        time_grid: jax.Array
            Array of time points for the SLIPS algorithm.
        batch_size: int
            Number of samples to generate.
        dim: int
            Dimension of the target distribution.
        params: SLIPSParams
            Parameters for the SLIPS algorithm (see `SLIPSParams` class).
    Returns 
    -------
    samples: jax.Array
        The final samples generated by the SLIPS algorithm.
    Y_hist: jax.Array
        The history of samples generated by the SLIPS algorithm.
    X_hist: jax.Array
        The history of MALA chains generated by the SLIPS algorithm.

    Example
    -------
    >>> key = jax.random.PRNGKey(42)
    >>> log_target = lambda x: -jnp.sum(((x-6)/2)**2)/2
    >>> time_grid = jnp.linspace(0.1,0.98)
    >>> batch_size = 2
    >>> dim = 1
    >>> params = SLIPSParams(10.0)
    >>> samples = slips(key, log_target, time_grid, batch_size, dim, params)
    >>> print(samples)
    """

    time_grid = params.schedule.validate_grid(time_grid)
    
    keys = random.split(key, batch_size)
    return _slips(keys, log_target, time_grid, dim, params)



    

    
    